Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 30
  WriteTimeout: 30

App:
  DefaultPageSize: 10
  MaxPageSize: 100

DataBase:
  UserName: root
  Password: zihuang2010=-0
  Host: rm-bp1303qu1t684d2kj.mysql.rds.aliyuncs.com
  Database: rblog
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConnections: 10
  MaxOpenConnections: 30
  MaxConnectionLifeTime: 30

Redis:
  Host: 172.18.0.5
  Port: 6379
  Address: ""
  Username: root
  Password: zihuang2010=-0
  Database: 0
  MasterName: ""
  MinIdleConns: 100
  MaxActive: 500
  EnableCluster: false
  Timeout: 30
